project:
  type: website

website:
  title: "Data Science @ The Strategy Unit"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - styles.scss
      - cosmo
    toc: true



