project:
  type: website

website:
  title: "Data Science @ The Strategy Unit"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: presentations/index.qmd
        text: Presentations

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



