project:
  type: website

website:
  title: "Data Science @ The Strategy Unit"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blogs/index.qmd
        text: Blogs
      - href: presentations/index.qmd
        text: Presentations

format:
  html:
    theme:
      light:
        - theme-light.scss
        - cosmo
      dark:
        - theme-dark.scss
        - cosmo

    toc: true



