---
title: "About"
---

The Data Science team at the Strategy Unit comprises the following team members:

- [Chris Beeley](https://github.com/ChrisBeeley)
- [Claire Welsh](https://github.com/DCEW)
- [Francis Barton](https://github.com/francisbarton)
- [Rhian Davies](https://github.com/statsRhian)
- [Matt Dray](https://github.com/matt-dray)
- [YiWen Hon](https://github.com/yiwen-h)
- [Tom Jemmett](https://github.com/tomjemmett)
- [Eirini Komninou](https://github.com/ai-mindset)
- [Ozayr Mohammed](https://github.com/O-Mohammed)
- [Natasha Stephenson](https://github.com/Nat-Stephenson)

The team has a wealth of experience in deploying models and other products to
the cloud for use by a wide range of users across health and care.
This is particularly demonstrated in our work with the New Hospital Programme,
where we built and deployed a sophisticated probabilistic demand and capacity
model and supported the use of its outputs across the decision-making stages
that lead to the construction of a new hospital.
The data science team possesses expertise across the breadth of data science
activity — for example, statistics, machine learning, natural language
processing, and real-time evidence mapping.
We also have significant experience in sharing our methods and code as
open-source, as well as in training others to use these tools and understand
foundational data science concepts and practices.
Our experience in developing scalable data science solutions, and
open-sourcing them for the benefit of users across the health and care sector,
enables us to contribute meaningfully at every stage of a project’s life cycle —
from design through to deployment and adoption.

Current and past projects of note include:

- Work supporting the New Hospitals Programme, including building a
  [model for predicting demand and capacity requirements for hospitals][nhpinfo]
  in the future, and [a tool for mapping the evidence on this topic][ev_maps].
- The [Patient Experience Qualitative Data Categorisation project][peqdc]
- Work supporting the wider analytical community, through events/communities
  such as [NHS-OA][nhsoa] and [HACA][haca].


[nhpinfo]: https://connect.strategyunitwm.nhs.uk/nhp/project_information/
[ev_maps]: https://github.com/The-Strategy-Unit/nhp_evidence_maps
[peqdc]: https://the-strategy-unit.github.io/PatientExperience-QDC/
[nhsoa]: https://nhsrcommunity.com/
[haca]: https://haca-conference.nhs.uk/
