# Team work

## Slack check-ins

On Fridays, at the end of each week and in advance of Monday's stand-up, all team members share a short summary, in Slack, answering the following questions:

- ⭐ What went well last week
- 🦉 What lessons did you learn
- 🎯 Goal(s) for this week

There is also a Slack bot every Tuesday and Thursday prompting a check-in. You don't have to respond to this, but it's a nice way to share any recent wins or blockers.

## Weekly stand up

Every Monday from 10:00 - 10:50 we have a team meeting.

We start with a stand-up from two team members. These are randomly selected by a bot on Slack in advance of the meeting.

If it's your week to talk, you have 5 minutes to chat about anything that matters to you. You could expand on your Slack stand-up, perhaps sharing your wins or learnings in more detail. You might also choose to share a project you are working on in, showing code or a shiny application. Chat about your weekend or an update on how you're doing is also totally fine!

We then discuss any items that team members have added to the [rolling agenda](https://docs.google.com/document/d/1WukwitMpDU9RexZaXHIvEf-vV6iGKLjCsdAVfKcIMPE/).

## Line management

Your line manager should arrange (1 : 1) meetings with you once a fortnight.

## Communication

We use MS Teams to communicate about project related work. 
We have a private slack channel on NHS-R slack which we use for general team chat and more casually. (Slack has much better emojis 🤸🎮🦥)

## Data Science Trophy 

One of the ways we celebrate each other and the successes we have is by presenting each other with a “trophy” 🏆 in the slack channel. This is for good code, problem solving, helping someone - anything that deserves a special mention.

## Working Times 

Core hours vary considerably between team members and there is a lot of flexibility. Team members may send messages out of hours, but that is purely because it works for them, and will not expect anything immediate in response. Flexibility is not only allowed but recommended if it benefits you. Please agree core hours with your line manager and where possible communicate any changes in your core hours to team members via out of office on your calendar and/or Slack (e.g. "I'm out all morning because my car is broken - working later on").

## Working Location

The team is primarily remote. The Strategy Unit has two all company gathering a year, in Birmingham. Currently the Data Science team don't have any in-person meetings, although we might start doing them occasionally when it's beneficial. Some of the London-based team coordinate when they work in the office.

## Task management

Most of the team's time is working on a large project which we manage in an agile-like manner. We use GitHub to capture issues, and a project board to manage the sprint. 

Tasks outside this project can be managed how you like. If you want to use GitHub, there is a [Data Science project planner](https://github.com/orgs/The-Strategy-Unit/projects/12).

## Coffee and Code

We organise a fortnightly coffee and code for analysts in the Strategy Unit. This is planned in a [Coffee and Coding ☕🧑‍💻 GitHub project](https://github.com/orgs/The-Strategy-Unit/projects/14). Materials from previous sessions are shared here as [blogs](../blogs/) or [presentations](../presentations/).

## Sidequests and support

We have a fortnightly Wednesday meeting for team members to discuss any interesting side projects or knotty issues. Three members of the team are randomly selected for this on Tuesday morning via Slack.
