---
title: "Text mining"
subtitle: "What it can and can't do, and what it could do"
author: 
  - "[Chris Beeley](mailto:chris.beeley1@nhs.net)"
date: 2024-11-27
date-format: "D MMMM YYYY"
format:
  revealjs:
    theme: [default, ../su_presentation.scss]
    transition: none
    chalkboard:
      buttons: false
    preview-links: auto
    slide-number: false
    auto-animate: true
    footer: |
      Learn more about [The Strategy Unit](https://www.strategyunitwm.nhs.uk/)
---

## Intro

* Range of possible applications
* There are a range of caveats depending on the use case
* Some of them are more relevant than others
* Some of them are "free", and some aren't

## What is text mining?

* A variety of supervised and unsupervised methods
* The uses we'll discuss today have no "understanding" of text (no "intelligence")
* They all have the potential, therefore, to be very inaccurate (e.g. negation)
* But they can be a low cost way of gathering insight, properly applied

## "I just want a bit of help sorting"

* This is one of the safer things to do
* There are a range of methods
* Some will give you some say of the "theme" of the piles, and some don't
* Great for: sifting, looking at relative size of piles, novel suggestions for themes for text
* Bad for: accuracy, control over what's in the piles

## "I just want to find useful examples"

* Also quite a safe application, and one we implemented for patient experience
* The algorithm is just helping you to find things with a particular theme or sentiment
* You bring the understanding

## "Free"