block-beta

columns 5

space space db[("Database")]:1 space space

space:5

space d("Storage: data"):1 space r("Storage: results"):1 space

space:5

i("App: inputs"):1
space
m("Model"):1
space
o("App: outputs"):1

db --> d
d --> i
m --> r
d --> m
r --> o
i --> m

style db fill:#686f73,stroke:#fff,color:#fff
style d fill:#5881c1,stroke:#fff,color:#fff
style r fill:#5881c1,stroke:#fff,color:#fff
style i fill:#f9bd07,stroke:#fff,color:#000
style m fill:#ec6555,stroke:#fff,color:#fff
style o fill:#f9bd07,stroke:#fff,color:#000
