name: rebuild-slides
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  rebuild-slides:
    name: rebuild-slides
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.github/workflows
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto
        uses: quarto-dev/quarto-actions/render@v2

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site/
          clean-exclude: pr-preview/
          force: false