name: rebuild-slides
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  rebuild-slides:
    name: rebuild-slides
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Install System Dependencies
        run: sudo apt install -y gdal-bin git libcurl4-openssl-dev libfontconfig1-dev libfreetype6-dev libfribidi-dev libgdal-dev libgeos-dev libglpk-dev libgmp3-dev libharfbuzz-dev libicu-dev libjpeg-dev libnode-dev libpng-dev libproj-dev libsqlite3-dev libssl-dev libtiff-dev libudunits2-dev libxml2-dev make pandoc zlib1g-dev

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
