name: rebuild-slides
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  rebuild-slides:
    name: rebuild-slides
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v4
        with:
          name: freeze
          path: _freeze

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y gdal-bin
          sudo apt install -y git
          sudo apt install -y libcurl4-openssl-dev
          sudo apt install -y libfontconfig1-dev
          sudo apt install -y libfreetype6-dev
          sudo apt install -y libfribidi-dev
          sudo apt install -y libgdal-dev
          sudo apt install -y libgeos-dev
          sudo apt install -y libglpk-dev
          sudo apt install -y libgmp3-dev
          sudo apt install -y libharfbuzz-dev
          sudo apt install -y libicu-dev
          sudo apt install -y libjpeg-dev
          sudo apt install -y libnode-dev
          sudo apt install -y libpng-dev
          sudo apt install -y libproj-dev
          sudo apt install -y libsqlite3-dev
          sudo apt install -y libssl-dev
          sudo apt install -y libtiff-dev
          sudo apt install -y libudunits2-dev
          sudo apt install -y libxml2-dev
          sudo apt install -y make
          sudo apt install -y pandoc
          sudo apt install -y zlib1g-dev

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages

      - uses: actions/upload-artifact@v4
        with:
          name: freeze
          path: _freeze