name: renew-cache
on:
  schedule:
    - cron: "0 10 * * *"

jobs:
  renew-cache:
    name: renew-cache
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v4
        with:
          key: freeze
          path: _freeze
